language: c++

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - CFLAGS_EXTRA_M=
  - CFLAGS_EXTRA_M=-m32
  - CONF_GCOV=--enable-gcov
  - CONF_GC_DEBUG=--enable-gc-debug

matrix:
  exclude:
  - os: osx
    compiler: gcc
  - compiler: clang
    env: CONF_GCOV=--enable-gcov
  - compiler: clang
    env: CONF_GC_DEBUG=--enable-gc-debug

sudo: required

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CFLAGS_EXTRA_M" == "-m32" ]]; then
      sudo apt-get install gcc-multilib;
    else
      CONF_CPP=--enable-cplusplus;
    fi
  - if [[ "$CONF_GCOV" == --en* ]]; then
      sudo apt-get install lcov;
      gem install coveralls-lcov;
      CONF_SHARED=--disable-shared;
      CONF_SINGLE_OBJ=--enable-single-obj-compilation;
    fi

install:
  - git clone --depth=50 https://github.com/ivmai/libatomic_ops.git
  - ./autogen.sh

script:
  - ./configure $CONF_CPP $CONF_GCOV $CONF_GC_DEBUG --enable-munmap $CONF_SHARED $CONF_SINGLE_OBJ --enable-werror
  - make -j check CFLAGS_EXTRA="$CFLAGS_EXTRA_M"

after_success:
  - if [[ "$CONF_GCOV" == --en* ]]; then
      lcov --capture --base-directory . --directory . --output-file coverage.info;
      lcov --remove coverage.info '/usr/*' 'cord/tests/*' 'libatomic_ops/*' 'tests/*' --output-file coverage.info;
      lcov --list coverage.info;
      coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info;
    fi
