language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

sudo: false

install:
  - git clone --depth=50 https://github.com/ivmai/libatomic_ops.git
  - ./autogen.sh

script:
  - ./configure --enable-cplusplus --enable-munmap --enable-werror
  - make -j check
