language: c++

matrix:
  include:
    - os: linux
      compiler: clang
      env: [ CONF_CPP=--enable-cplusplus ]
    - os: linux
      compiler: gcc
      env: [ CONF_CPP=--enable-cplusplus ]
    - os: osx
      env: [ CONF_CPP=--enable-cplusplus ]
    - os: linux
      addons: { apt: { packages: [ gcc-multilib ] } }
      compiler: clang
      env: [ CFLAGS_EXTRA="-m32", CONF_ASSERTIONS=--enable-gc-assertions ]
    - os: linux
      addons: { apt: { packages: [ gcc-multilib ] } }
      compiler: gcc
      env: [ CFLAGS_EXTRA="-m32", CONF_ASSERTIONS=--enable-gc-assertions ]
    - os: osx
      env:
        - CFLAGS_EXTRA="-m32"
        - CONF_ASSERTIONS=--enable-gc-assertions
        - CONF_CPP=--enable-cplusplus
    - os: linux
      compiler: gcc
      env: [ CONF_GC_DEBUG=--enable-gc-debug, CONF_CPP=--enable-cplusplus ]
    - os: linux
      compiler: gcc
      env: [ CONF_GC_DEBUG=--disable-gc-debug, CONF_CPP=--enable-cplusplus ]
    - os: linux
      compiler: clang
      env:
        - CONF_LARGE_CONFIG=--enable-large-config
        - CONF_M_UNMAP=--enable-munmap
        - CONF_CPP=--enable-cplusplus
    - os: osx
      env:
        - CONF_LARGE_CONFIG=--enable-large-config
        - CONF_M_UNMAP=--enable-munmap
        - CONF_CPP=--enable-cplusplus
    - os: linux
      compiler: clang
      env:
        - CONF_STATIC=--disable-static
        - CONF_THREADS=--disable-threads
        - CFLAGS_EXTRA="-O3 -march=native"
        - CONF_ASSERTIONS=--enable-gc-assertions
        - CONF_CPP=--enable-cplusplus
    - os: linux
      compiler: gcc
      env:
        - CONF_STATIC=--disable-static
        - CONF_THREADS=--disable-threads
        - CFLAGS_EXTRA="-O3 -march=native"
        - CONF_ASSERTIONS=--enable-gc-assertions
        - CONF_CPP=--enable-cplusplus
    - os: osx
      env:
        - CONF_STATIC=--disable-static
        - CONF_THREADS=--disable-threads
        - CFLAGS_EXTRA="-O3 -march=native"
        - CONF_ASSERTIONS=--enable-gc-assertions
        - CONF_CPP=--enable-cplusplus

install:
  - git clone --depth=50 https://github.com/ivmai/libatomic_ops.git -b release-7_4
  - ./autogen.sh

script:
  - ./configure $CONF_ASSERTIONS $CONF_CPP $CONF_GC_DEBUG $CONF_LARGE_CONFIG
                $CONF_M_UNMAP $CONF_STATIC $CONF_THREADS
  - make -j check CFLAGS_EXTRA="$CFLAGS_EXTRA"
