language: c++

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - CFLAGS_EXTRA_M=
  - CFLAGS_EXTRA_M=-m32
  - CONF_GC_DEBUG=--enable-gc-debug

matrix:
  exclude:
  - os: osx
    compiler: gcc
  - compiler: clang
    env: CONF_GC_DEBUG=--enable-gc-debug

sudo: required

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CFLAGS_EXTRA_M" == "-m32" ]]; then
      sudo apt-get install gcc-multilib;
    else
      CONF_CPP=--enable-cplusplus;
    fi

install:
  - git clone --depth=50 https://github.com/ivmai/libatomic_ops.git -b release-7_4
  - ./autogen.sh

script:
  - ./configure $CONF_CPP $CONF_GC_DEBUG --enable-munmap
  - make -j check CFLAGS_EXTRA="$CFLAGS_EXTRA_M"
