language: c++

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - CONF_GC_DEBUG=
  - CONF_ASSERTIONS=--enable-gc-assertions
  - CONF_GC_DEBUG=--enable-gc-debug
  - CONF_GC_DEBUG=--disable-gc-debug
  - CONF_LARGE_CONFIG=--enable-large-config
  - CONF_STATIC=--disable-static
      CONF_THREADS=--disable-threads
      CONF_ASSERTIONS=--enable-gc-assertions

matrix:
  exclude:
  - os: osx
    compiler: gcc
  - compiler: clang
    env: CONF_GC_DEBUG=--enable-gc-debug
  - compiler: clang
    env: CONF_GC_DEBUG=--disable-gc-debug
  - compiler: gcc
    env: CONF_LARGE_CONFIG=--enable-large-config

sudo: false

install:
  - git clone --depth=50 https://github.com/ivmai/libatomic_ops.git -b release-7_2
  - autoreconf -vif

script:
  - ./configure $CONF_ASSERTIONS --enable-cplusplus $CONF_GC_DEBUG
                $CONF_LARGE_CONFIG $CONF_STATIC $CONF_THREADS
  - make -j check
