language: c++

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - CFLAGS_EXTRA_M=
  - CFLAGS_EXTRA_M=-m32
      CONF_ASSERTIONS=--enable-gc-assertions
  - CONF_GC_DEBUG=--enable-gc-debug
  - CONF_GC_DEBUG=--disable-gc-debug
  - CONF_LARGE_CONFIG=--enable-large-config
  - CONF_STATIC=--disable-static
      CONF_THREADS=--disable-threads
      CONF_ASSERTIONS=--enable-gc-assertions
      CFLAGS_EXTRA="-O3 -march=native"

matrix:
  exclude:
  - os: osx
    compiler: gcc
  - compiler: clang
    env: CONF_GC_DEBUG=--enable-gc-debug
  - compiler: clang
    env: CONF_GC_DEBUG=--disable-gc-debug
  - compiler: gcc
    env: CONF_LARGE_CONFIG=--enable-large-config

sudo: required

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CFLAGS_EXTRA_M" == "-m32" ]]; then
      sudo apt-get install gcc-multilib;
    else
      CONF_CPP=--enable-cplusplus;
    fi

install:
  - git clone --depth=50 https://github.com/ivmai/libatomic_ops.git -b release-7_4
  - ./autogen.sh

script:
  - ./configure $CONF_ASSERTIONS $CONF_CPP $CONF_GC_DEBUG $CONF_LARGE_CONFIG
                --enable-munmap $CONF_STATIC $CONF_THREADS
  - make -j check CFLAGS_EXTRA="$CFLAGS_EXTRA $CFLAGS_EXTRA_M"
