language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

sudo: false

install:
  - git clone --depth=50 https://github.com/ivmai/libatomic_ops.git -b release-7_2
  - autoreconf -vif

script:
  - ./configure
  - make -j check
