language: c++

matrix:
  include:
  - os: linux
    compiler: clang
    env:
    - CONF_OPTIONS="--enable-cplusplus"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: linux
    compiler: gcc
    env:
    - CONF_OPTIONS="--enable-cplusplus"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: osx
    env:
    - CONF_OPTIONS="--enable-cplusplus"
  - os: linux
    env:
    - MAKEFILE_TARGETS="dist"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: linux
    addons:
      apt:
        packages:
        - libatomic-ops-dev
    compiler: clang
    dist: trusty
    env:
    - CONF_OPTIONS="--enable-cplusplus"
    - NO_CLONE_LIBATOMIC_OPS=true
  - os: linux
    addons:
      apt:
        packages:
        - libatomic-ops-dev
    compiler: gcc
    dist: trusty
    env:
    - CONF_OPTIONS="--enable-gc-assertions --enable-cplusplus"
    - NO_CLONE_LIBATOMIC_OPS=true
  - os: linux
    compiler: clang
    env:
    - CONF_OPTIONS="--enable-gc-assertions"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: linux
    compiler: gcc
    env:
    - CONF_OPTIONS="--enable-gc-assertions"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: osx
    env:
    - CONF_OPTIONS="--enable-gc-assertions --enable-cplusplus"
  - os: linux
    compiler: gcc
    env:
    - CONF_OPTIONS="--enable-gc-debug --enable-cplusplus"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: linux
    compiler: gcc
    env:
    - CONF_OPTIONS="--disable-gc-debug --enable-cplusplus"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: linux
    compiler: clang
    env:
    - CONF_OPTIONS="--enable-large-config --enable-cplusplus"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: osx
    env:
    - CONF_OPTIONS="--enable-large-config --enable-cplusplus"
  - os: linux
    compiler: gcc
    env:
    - CONF_OPTIONS="--enable-large-config"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: linux
    compiler: gcc
    env:
    - CONF_OPTIONS="--enable-large-config --enable-munmap --enable-cplusplus"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: linux
    compiler: clang
    env:
    - CONF_OPTIONS="--enable-redirect-malloc --disable-threads"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: osx
    env:
    - CONF_OPTIONS="--enable-redirect-malloc --enable-cplusplus --disable-threads"
  - os: linux
    compiler: gcc
    env:
    - CONF_OPTIONS="--enable-redirect-malloc --enable-gc-debug --enable-cplusplus --enable-gc-assertions"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: linux
    compiler: clang
    env:
    - CONF_OPTIONS="--disable-static --disable-threads --enable-cplusplus"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: linux
    compiler: gcc
    env:
    - CONF_OPTIONS="--disable-static --disable-threads --enable-cplusplus"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: osx
    env:
    - CONF_OPTIONS="--disable-static --disable-threads --enable-cplusplus"

before_install:
- if [[ "$MAKEFILE_TARGETS" == "" ]]; then MAKEFILE_TARGETS="check"; fi

install:
- if [[ "$NO_CLONE_LIBATOMIC_OPS" != true ]]; then
    git clone --depth=50 https://github.com/ivmai/libatomic_ops.git
              -b release-7_2;
  fi
- if [[ "$WORKAROUND_ACLOCAL_MISSING" == true ]]; then
    autoreconf --force --install;
  fi

script:
- ./configure $CONF_OPTIONS
- make -j $MAKEFILE_TARGETS
