language: c++

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - CONF_GC_DEBUG=
  - CONF_GC_DEBUG=--enable-gc-debug

matrix:
  exclude:
  - os: osx
    compiler: gcc
  - compiler: clang
    env: CONF_GC_DEBUG=--enable-gc-debug

sudo: false

install:
  - git clone --depth=50 https://github.com/ivmai/libatomic_ops.git -b release-7_2
  - autoreconf -vif

script:
  - ./configure --enable-cplusplus $CONF_GC_DEBUG
  - make -j check
