language: c++

matrix:
  include:
    - os: linux
      compiler: clang
      env: [ CONF_OPTIONS="--enable-cplusplus" ]
    - os: linux
      compiler: gcc
      env: [ CONF_OPTIONS="--enable-cplusplus" ]
    - os: osx
      env: [ CONF_OPTIONS="--enable-cplusplus" ]
    - os: linux
      addons: { apt: { packages: [ gcc-multilib ] } }
      compiler: clang
      env: [ CFLAGS_EXTRA="-m32", CONF_OPTIONS="--enable-gc-assertions" ]
    - os: linux
      addons: { apt: { packages: [ gcc-multilib ] } }
      compiler: gcc
      env: [ CFLAGS_EXTRA="-m32", CONF_OPTIONS="--enable-gc-assertions" ]
    - os: osx
      env:
        - CFLAGS_EXTRA="-m32"
        - CONF_OPTIONS="--enable-gc-assertions --enable-cplusplus"
    - os: linux
      compiler: gcc
      env: [ CONF_OPTIONS="--enable-gc-debug --enable-cplusplus" ]
    - os: linux
      compiler: gcc
      env: [ CONF_OPTIONS="--disable-gc-debug --enable-cplusplus" ]
    - os: linux
      compiler: clang
      env:
        - CONF_OPTIONS="--enable-large-config --enable-munmap --enable-cplusplus"
    - os: osx
      env:
        - CONF_OPTIONS="--enable-large-config --enable-munmap --enable-cplusplus"
    - os: linux
      compiler: clang
      env:
        - CONF_OPTIONS="--disable-static --disable-threads --enable-gc-assertions --enable-cplusplus"
        - CFLAGS_EXTRA="-O3 -march=native"
    - os: linux
      compiler: gcc
      env:
        - CONF_OPTIONS="--disable-static --disable-threads --enable-gc-assertions --enable-cplusplus"
        - CFLAGS_EXTRA="-O3 -march=native"
    - os: osx
      env:
        - CONF_OPTIONS="--disable-static --disable-threads --enable-gc-assertions --enable-cplusplus"
        - CFLAGS_EXTRA="-O3 -march=native"

install:
  - git clone --depth=50 https://github.com/ivmai/libatomic_ops.git -b release-7_4
  - ./autogen.sh

script:
  - ./configure $CONF_OPTIONS
  - cat include/config.h
  - make -j check CFLAGS_EXTRA="$CFLAGS_EXTRA"
  - if [ -f gctest.log ]; then cat gctest.log; fi
